version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    container_name: react_redux_base
    environment:
      - NODE_ENV=development
    image: styers/react-redux-base:latest
    restart: on_failure