version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    environment:
      - NODE_ENV=development
    image: styers/react-redux-base:latest
    restart: on_failure
  yarn:
    build:
      context: .
      dockerfile: Dockerfiles/yarn.Dockerfile
    environment:
      - NODE_ENV=development
    image: styers/react-redux-base:yarn
    restart: on_failure