version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    container_name: react_redux_base
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
    image: styers/react-redux-base
    ports:
      - "80:8080"
    restart: on_failure
    working_dir: /app/base
    volumes:
      - .:/app/base
  webpackv1:
    build:
      context: .
      dockerfile: Dockerfiles/webpackv1.Dockerfile
    container_name: react_redux_base_webpackv1
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
    image: styers/react-redux-base:webpackv1
    ports:
      - "80:8080"
    restart: on_failure
    working_dir: /app/base
    volumes:
      - .:/app/base
  nodev6:
    build:
      context: .
      dockerfile: Dockerfiles/691.Dockerfile
    container_name: react_redux_base_nodev6
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
    image: styers/react-redux-base:6.9.1
    ports:
      - "80:8080"
    restart: on_failure
    working_dir: /app/base
    volumes:
      - .:/app/base
